### PR TITLE
Add format section into the project setting page.

### PR DESCRIPTION
**Pull request by jdneo**
- Click the formatter from nav side will open a new window for formatter page.
- Move the project select to the top level of the page.
- Move the apply button to the top level of the page.

### CODE REVIEW

**Comment by jdneo** [comment]
https://github.com/microsoft/vscode-java-pack/assets/6193897/360b6d68-a738-4cc1-bd34-2a5435081c58

**Review by testforstephen — APPROVED** [review]
LGTM. One minor issue is that when I use "Configure Java Runtime" command to open the webview, it doesn't jump to the JDK tab page at the first time.

**Comment by jdneo** [comment]
> when I use "Configure Java Runtime" command to open the webview, it doesn't jump to the JDK tab page at the first time.

Tracked by https://github.com/microsoft/vscode-java-pack/issues/1330

**Comment by SERE026** [comment]
image
@[jdneo](https://github.com/jdneo) jdneo mentioned this pull request [on May 20](https://github.com/microsoft/vscode-java-pack/pull/1324#ref-issue-2267309680)
https://github.com/microsoft/vscode-java-pack/issues/1316

**Pull request merged**
