### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by Eskibear**
- npm update
- remove `node-sass` as it's not used.

### CODE REVIEW

**Comment by CsCherrYY** [comment]
ci failed. I remember `node-sass` is required as a peer dependency...

**Comment by Eskibear** [comment]
node-sass is deprecated. maybe we should migrate to dart-sass

see https://sass-lang.com/blog/libsass-is-deprecated#how-do-i-migrate

**Comment by Eskibear** [comment]
@CsCherrYY I'll add node-sass back for the moment. Please help to keep an eye on how to migrate our project to dart-sass, in case of future CVE.

**Comment by CsCherrYY** [comment]
I'll track it in #872

**Review by CsCherrYY — APPROVED** [review]

**Pull request merged**
