### PR TITLE
Add IBM Semeru Runtimes to Other JDKs list

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@Eskibear for review please.
Also see https://github.com/microsoft/vscode-docs/pull/5784

I'm not sure if I need any other changes or if this is complete.
Thanks

**Comment by Eskibear** [comment]
+ @nickzhums for awareness.

**Comment by nickzhums** [comment]
Hi @AdamBrousseau, thanks for submitting the PR. This is Nick and I'm the PM for VS Code Java. Feel free to ping us if you have other questions in the future.

**Review by Eskibear — APPROVED** [review]
keep consistence with docs.

**Pull request merged**
